name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

env:
  REGISTRY: docker.io
  IMAGE_NAME: hshekhar7/event  # Replace with your Docker Hub username and repository name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log i
